---
- name: Run K3s Uninstall script [server]
  when: "'server' in group_names"
  ansible.builtin.command:
    cmd: k3s-uninstall.sh
    removes: /var/lib/rancher/k3s/*

- name: Run K3s Uninstall script [agent]
  when: "'agent' in group_names"
  ansible.builtin.command:
    cmd: k3s-agent-uninstall.sh
    removes: /var/lib/rancher/k3s/*

- name: Ensure K3s directories are removed after uninstall [server]
  ansible.builtin.file:
    path: /var/lib/rancher/k3s
    state: absent
  when: "'server' in group_names"

- name: Remove user kubeconfig
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube/config
    state: absent

- name: Remove main installation folder
  ansible.builtin.shell:
    cmd: "rm -rf /home/{{ ansible_user }}/.k3s/*"
    removes: "/home/{{ ansible_user }}/.k3s/*"
